import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { combineLatest, map } from 'rxjs';
import { DashboardDataService } from '../../core/services/dashboard-data.service';
import { ActivityType, CaseItem, PeriodRange, ProfessionalRecord, ProfessionalRecordInput, TaskItem } from './productivity.models';
import { ProductivityRecordsService } from './productivity-records.service';

type Period='day'|'week'|'month'|'quarter'|'year'|'history'|'custom';
type View='analysis'|'journal'|'report';
@Component({selector:'app-productivity',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./productivity.component.html',styleUrls:['./productivity.component.scss']})
export class ProductivityComponent implements OnInit {
  readonly data=inject(DashboardDataService); private readonly api=inject(ProductivityRecordsService);
  readonly vm$=combineLatest([this.data.tasks$,this.data.cases$]).pipe(map(([tasks,cases])=>({tasks:tasks as TaskItem[],cases:cases as CaseItem[]})));
  readonly activityTypes:{value:ActivityType;label:string}[]=[{value:'Migration',label:'Migración'},{value:'Case',label:'Caso'},{value:'Certification',label:'Certificación'},{value:'Development',label:'Desarrollo'},{value:'Other',label:'Otra actividad'}];
  view:View='analysis'; period:Period='month'; customFrom=''; customTo=''; customError=''; showManualRange=false;
  records:ProfessionalRecord[]=[]; recordsLoading=false; recordsError=''; editorOpen=false; saving=false; editingId?:number; recordForm=this.emptyRecord();
  ngOnInit(){this.loadRecords();}
  private emptyRecord():ProfessionalRecordInput{return{activityType:'Other',date:new Date().toISOString().slice(0,10),relatedActivityId:'',relatedActivityName:'',result:'',challenge:'',solution:'',learning:'',improvementArea:'',notes:''};}
  selectPeriod(period:Exclude<Period,'custom'>){this.period=period;this.customError='';this.showManualRange=false;}
  applyCustom(){if(!this.customFrom||!this.customTo){this.customError='Selecciona ambas fechas.';return;}if(this.customFrom>this.customTo){this.customError='La fecha inicial debe ser anterior a la final.';return;}this.customError='';this.period='custom';this.showManualRange=false;}
  clearCustom(){this.customFrom='';this.customTo='';this.period='month';this.showManualRange=false;}
  range(period=this.period,offset=0):PeriodRange{const now=new Date();let start:Date|undefined,end:Date|undefined;if(period==='history')return{label:'Histórico completo'};if(period==='custom')return{start:this.localDate(this.customFrom),end:this.endDate(this.customTo),label:`${this.formatDate(this.customFrom)} – ${this.formatDate(this.customTo)}`};if(period==='day'){start=new Date(now.getFullYear(),now.getMonth(),now.getDate()+offset);end=this.endOfDay(start);}if(period==='week'){start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7)+offset*7);start.setHours(0,0,0,0);end=new Date(start);end.setDate(end.getDate()+6);end=this.endOfDay(end);}if(period==='month'){start=new Date(now.getFullYear(),now.getMonth()+offset,1);end=this.endOfDay(new Date(now.getFullYear(),now.getMonth()+offset+1,0));}if(period==='quarter'){const base=Math.floor(now.getMonth()/3)*3+offset*3;start=new Date(now.getFullYear(),base,1);end=this.endOfDay(new Date(now.getFullYear(),base+3,0));}if(period==='year'){start=new Date(now.getFullYear()+offset,0,1);end=this.endOfDay(new Date(now.getFullYear()+offset,11,31));}return{start,end,label:start&&end?`${this.formatDate(start)} – ${this.formatDate(end)}`:'Periodo'};}
  filtered(tasks:TaskItem[],range=this.range()){return tasks.filter(t=>{
    const finished=Number(t.completionPercent)>=100;
    if(finished&&!t.completedAt)return this.period==='history';
    return this.inRange(finished?t.completedAt:t.startAt,range);
  });}
  filteredCases(cases:CaseItem[],range=this.range()){return cases.filter(c=>this.inRange(c.lastOutgoingAt||c.lastIncomingAt||c.createdAt,range));}
  filteredRecords(range=this.range()){return this.records.filter(r=>this.inRange(r.date,range));}
  completed(tasks:TaskItem[]){return tasks.filter(t=>Number(t.completionPercent)>=100).length;}
  overdue(tasks:TaskItem[]){return tasks.filter(t=>t.dueAt&&new Date(t.dueAt)<new Date()&&Number(t.completionPercent)<100&&!`${t.status||''}`.toLowerCase().includes('cancel')).length;}
  average(tasks:TaskItem[]){return tasks.length?Math.round(tasks.reduce((s,t)=>s+Number(t.completionPercent||0),0)/tasks.length):0;}
  completionRate(tasks:TaskItem[]){return tasks.length?Math.round(this.completed(tasks)/tasks.length*100):0;}
  previous(tasks:TaskItem[]){return this.filtered(tasks,this.range(this.period,-1));}
  delta(current:number,previous:number){return previous?Math.round((current-previous)/previous*100):current?100:0;}
  categories(tasks:TaskItem[]){const m=new Map<string,number>();tasks.forEach(t=>m.set(t.category||'Sin categoría',(m.get(t.category||'Sin categoría')||0)+1));return[...m].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count);}
  countCategory(tasks:TaskItem[],text:string){return tasks.filter(t=>`${t.category||''}`.toLowerCase().includes(text)).length;}
  max(items:{count:number}[]){return Math.max(1,...items.map(x=>x.count));}
  typeLabel(type:ActivityType){return this.activityTypes.find(x=>x.value===type)?.label||type;}
  timeline(tasks:TaskItem[]){const range=this.range();if(!range.start||!range.end)return this.yearlyTimeline(tasks);const days=Math.max(1,Math.ceil((range.end.getTime()-range.start.getTime())/86400000)),step=days<=14?1:days<=100?7:31,points:{label:string;started:number;completed:number}[]=[];for(let cursor=new Date(range.start);cursor<=range.end;){const next=step===31?new Date(cursor.getFullYear(),cursor.getMonth()+1,1):new Date(cursor.getFullYear(),cursor.getMonth(),cursor.getDate()+step);points.push({label:cursor.toLocaleDateString('es-MX',step===31?{month:'short'}:{day:'numeric',month:'short'}),started:tasks.filter(t=>this.between(t.startAt,cursor,next)).length,completed:tasks.filter(t=>this.between(t.completedAt,cursor,next)).length});cursor=next;}return points;}
  timelineMax(points:{started:number;completed:number}[]){return Math.max(1,...points.flatMap(x=>[x.started,x.completed]));}
  relatedActivities(tasks:TaskItem[],cases:CaseItem[]){if(this.recordForm.activityType==='Case')return cases.map(c=>({id:c.caseNumber||'',name:`${c.caseNumber||'Caso'} · ${c.subject||'Sin asunto'}`}));const match:Record<ActivityType,(v:string)=>boolean>={Migration:v=>v.includes('migr'),Certification:v=>v.includes('cert'),Development:v=>v.includes('desarroll'),Other:()=>true,Case:()=>false};return tasks.filter(t=>match[this.recordForm.activityType](`${t.category||''}`.toLowerCase())).map(t=>({id:t.externalId||t.summary||'',name:t.summary||'Actividad sin nombre'}));}
  relatedChanged(tasks:TaskItem[],cases:CaseItem[]){this.recordForm.relatedActivityName=this.relatedActivities(tasks,cases).find(x=>x.id===this.recordForm.relatedActivityId)?.name||'';}
  newRecord(){this.editingId=undefined;this.recordForm=this.emptyRecord();this.editorOpen=true;}
  editRecord(r:ProfessionalRecord){this.editingId=r.id;this.recordForm={activityType:r.activityType,relatedActivityId:r.relatedActivityId||'',relatedActivityName:r.relatedActivityName||'',result:r.result||'',challenge:r.challenge||'',solution:r.solution||'',learning:r.learning||'',improvementArea:r.improvementArea||'',date:r.date.slice(0,10),notes:r.notes||''};this.editorOpen=true;}
  saveRecord(){if(!this.recordForm.date)return;this.saving=true;const call=this.editingId?this.api.update(this.editingId,this.recordForm):this.api.create(this.recordForm);call.subscribe({next:()=>{this.saving=false;this.editorOpen=false;this.loadRecords();this.data.notify('Registro profesional guardado.','success');},error:()=>{this.saving=false;this.data.notify('No fue posible guardar el registro.','error');}});}
  deleteRecord(r:ProfessionalRecord){if(!confirm('¿Eliminar este registro profesional?'))return;this.api.remove(r.id).subscribe({next:()=>{this.loadRecords();this.data.notify('Registro eliminado.','info');},error:()=>this.data.notify('No fue posible eliminar el registro.','error')});}
  loadRecords(){this.recordsLoading=true;this.api.list().subscribe({next:items=>{this.records=items||[];this.recordsLoading=false;this.recordsError='';},error:()=>{this.records=[];this.recordsLoading=false;this.recordsError='La bitácora profesional no está disponible.';}});}
  exportExcel(tasks:TaskItem[],cases:CaseItem[]){const ts=this.filtered(tasks),cs=this.filteredCases(cases),rs=this.filteredRecords(),rows:(string|number)[][]=[['REPORTE DE DESEMPEÑO',this.range().label],[],['INDICADORES CALCULADOS'],['Tareas del periodo',ts.length],['Tareas completadas',this.completed(ts)],['Cumplimiento',`${this.completionRate(ts)}%`],['Casos con actividad',cs.length],[],['ACTIVIDADES'],['Tipo','Actividad','Estado','Fecha']];ts.forEach(t=>rows.push(['Tarea',t.summary||'',t.status||'',t.completedAt||t.startAt||'']));cs.forEach(c=>rows.push(['Caso',`${c.caseNumber||''} ${c.subject||''}`,c.status||'',c.lastOutgoingAt||c.lastIncomingAt||c.createdAt||'']));rows.push([],['REGISTROS MANUALES'],['Tipo','Actividad relacionada','Resultado','Aprendizaje','Área de mejora','Fecha']);rs.forEach(r=>rows.push([this.typeLabel(r.activityType),r.relatedActivityName||'',r.result||'',r.learning||'',r.improvementArea||'',r.date]));const csv=rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');this.download(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}),`reporte-desempeno-${new Date().toISOString().slice(0,10)}.csv`);}
  exportPdf(tasks:TaskItem[],cases:CaseItem[]){const ts=this.filtered(tasks),cs=this.filteredCases(cases),rs=this.filteredRecords(),popup=window.open('','_blank','width=980,height=760');if(!popup){this.data.notify('El navegador bloqueó la ventana de impresión.','error');return;}const rows=rs.map(r=>`<tr><td>${this.escape(this.typeLabel(r.activityType))}</td><td>${this.escape(r.relatedActivityName||'Sin relación')}</td><td>${this.escape(r.result||'—')}</td><td>${this.escape(r.learning||'—')}</td></tr>`).join('');popup.document.write(`<html><head><title>Reporte de desempeño</title><style>body{font:13px Arial;color:#132d46;margin:40px}h1{margin-bottom:4px}.sub{color:#60768a}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.kpis div{border:1px solid #dbe4eb;border-radius:8px;padding:14px}.kpis b{display:block;font-size:24px;margin-top:7px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{text-align:left;border-bottom:1px solid #dbe4eb;padding:9px}th{background:#eef4f7;font-size:10px}.note{margin-top:24px;color:#60768a;font-size:11px}@media print{body{margin:18mm}}</style></head><body><h1>Reporte de desempeño</h1><div class="sub">${this.escape(this.range().label)} · Generado ${new Date().toLocaleString('es-MX')}</div><section class="kpis"><div>Tareas registradas<b>${ts.length}</b></div><div>Completadas<b>${this.completed(ts)}</b></div><div>Cumplimiento<b>${this.completionRate(ts)}%</b></div><div>Casos con actividad<b>${cs.length}</b></div></section><h2>Evolución profesional</h2>${rows?`<table><thead><tr><th>Tipo</th><th>Actividad</th><th>Resultado</th><th>Aprendizaje</th></tr></thead><tbody>${rows}</tbody></table>`:'<p>No hay registros manuales en el periodo.</p>'}<p class="note">Los indicadores provienen de actividades del sistema. Resultados y aprendizajes son observaciones registradas manualmente por el usuario.</p><script>window.onload=()=>window.print()</script></body></html>`);popup.document.close();}
  private yearlyTimeline(tasks:TaskItem[]){const years=[...new Set(tasks.map(t=>new Date(t.completedAt||t.startAt||'').getFullYear()).filter(Boolean))].sort();return years.map(y=>({label:`${y}`,started:tasks.filter(t=>t.startAt&&new Date(t.startAt).getFullYear()===y).length,completed:tasks.filter(t=>t.completedAt&&new Date(t.completedAt).getFullYear()===y).length}));}
  private inRange(value:string|undefined,range:PeriodRange){if(!value)return false;if(!range.start||!range.end)return true;const d=new Date(value);return d>=range.start&&d<=range.end;}
  private between(value:string|undefined,start:Date,end:Date){if(!value)return false;const d=new Date(value);return d>=start&&d<end;}
  private localDate(value:string){return value?new Date(`${value}T00:00:00`):undefined;}
  private endDate(value:string){return value?new Date(`${value}T23:59:59.999`):undefined;}
  private endOfDay(value:Date){const d=new Date(value);d.setHours(23,59,59,999);return d;}
  private formatDate(value:Date|string){const d=typeof value==='string'?this.localDate(value):value;return d?.toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})||'';}
  private download(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.style.display='none';document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
  private escape(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
}
